### ISSUE TITLE
Building docs with MarkdownParser fails

### ISSUE THREAD

**Issue by nsoranzo** [codejamninja/sphinx-markdown-parser#6]
```
...
reading sources... [  0%] admin/apache                                                                                                                                                                             
Exception occurred:
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/parsers/rst/directives/misc.py", line 70, in run
    'tab-width', self.state.document.settings.tab_width)
AttributeError: 'Values' object has no attribute 'tab_width'
The full traceback has been saved in /tmp/sphinx-err-1mp3d5m2.log, if you want to report the issue to the developers.
```

/tmp/sphinx-err-1mp3d5m2.log contains:
```
# Sphinx version: 2.2.0
# Python version: 3.6.8 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   building [html]: targets for 244 source files that are out of date
#   
#   updating environment:
#   
#   [new config]
#   
#   244 added, 0 changed, 0 removed
#   
#   reading sources... [  0%] admin/apache
#   
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.0) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (2.2.0) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (2.2.0) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.doctest (2.2.0) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.todo (2.2.0) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (2.2.0) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.viewcode (2.2.0) from /usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/ext/viewcode.py
Traceback (most recent call last):
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/application.py", line 346, in build
    self.builder.build_update()
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/io.py", line 326, in read_doc
    pub.publish()
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    super().apply_transforms()
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx_markdown_parser/transform.py", line 342, in apply
    self.traverse(self.document)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx_markdown_parser/transform.py", line 320, in traverse
    self.traverse(child)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx_markdown_parser/transform.py", line 320, in traverse
    self.traverse(child)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx_markdown_parser/transform.py", line 310, in traverse
    newnode = self.find_replace(c)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx_markdown_parser/transform.py", line 292, in find_replace
    newnode = self.auto_code_block(node)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx_markdown_parser/transform.py", line 257, in auto_code_block
    match_titles=True
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/sphinx/directives/other.py", line 383, in run
    return super().run()
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv3/lib/python3.6/site-packages/docutils/parsers/rst/directives/misc.py", line 70, in run
    'tab-width', self.state.document.settings.tab_width)
AttributeError: 'Values' object has no attribute 'tab_width'
```

Using `CommonMarkParser` works, but Markdown tables are not translated to HTML tables.

I think `CommonMarkParser` works because of this workaround in Sphinx: https://github.com/sphinx-doc/sphinx/pull/5052

**Comment by clayrisser** [comment]
Use the MarkdownParser. I don't maintain the CommonmarkParser. The entire reason I built this was so I could add the MarkdownParser because the CommonmarkParser doesn't support features like tables.

**Comment by nsoranzo** [comment]
I tried the MarkdownParser but it fails with the error above.

**Comment by clayrisser** [comment]
Ok thanks for trying it. Could you send me a link to your setup and I'll debug it?

**Comment by nsoranzo** [comment]
I've given this another try and this starts to happen only if I add:

```python
        'extensions': [
            'extra',
        ]
```

to `conf.py` (other extensions work fine).

and goes away if I remove all `eval_rst` block containing `.. include::` ~or which are indented~.

The full traceback for https://github.com/galaxyproject/galaxy/blob/dev/doc/source/admin/apache.md is at https://gist.github.com/nsoranzo/c4ebe2d4f21e9141cd23c0dcaf6399dc

**Comment by clayrisser** [comment]
@nsoranzo thanks for filing this issue. I am not actively developing this project, so I do not know when I will get around to it. Feel free to submit a pull request if you find a fix, and I will merge it in.

**Comment by nsoranzo** [comment]
OK, thanks for letting me know! Before I go into a rabbit hole, is it OK to use `AutoStructify` with the `MarkdownParser`? I.e. having in `conf.py`:

```python
    app.add_source_suffix('.md', 'markdown')
    app.add_source_parser(MarkdownParser)
    app.add_config_value('markdown_parser_config', {
        'enable_auto_doc_ref': False,
        'enable_auto_toc_tree': False,
        'enable_eval_rst': True,
        'extensions': [
            'extra',
            'nl2br',
            'sane_lists',
        ]
    }, True)
    app.add_transform(AutoStructify)
```

It's not very clear from the README.

**Comment by clayrisser** [comment]
If I remember correctly, you should be able to use it. Let me know if it doesn't work.

**Comment by infinity0** [comment]
@nsoranzo A few months ago I rewrote markdown_parser in #8 and we are using it in https://github.com/w3f/research/blob/master/docs/conf.py#L86, does that example help?

**Comment by infinity0** [comment]
I think `AutoStructify` should be redundant with `markdown_parser` since it uses hooks specific to the other one (memory fuzzy, can't remember details now)

**Comment by thibaudcolas** [comment]
Same error here, this is specifically an issue with autodoc features such as `include` (for me it’s `autofunction`).

This works just fine with recommonmark:

    ```eval_rst
    .. module:: wagtail.core.utils

    .. autofunction:: cautious_slugify
    ```

With this parser and Sphinx 2, I get:

```
[...]/sphinx/ext/autodoc/__init__.py", line 430, in get_doc
    tab_width = self.directive.state.document.settings.tab_width
AttributeError: 'Values' object has no attribute 'tab_width'
```

With Sphinx 3,

```
WARNING: error while formatting signature for wagtail.core.utils.cautious_slugify: 'Values' object has no attribute 'tab_width'
```

There’s nothing particularly exciting to that function’s docstring,

```python
def cautious_slugify(value):
    """
    Convert a string to ASCII exactly as Django's slugify does, with the exception
    that any non-ASCII alphanumeric characters (that cannot be ASCIIfied under Unicode
    normalisation) are escaped into codes like 'u0421' instead of being deleted entirely.
    This ensures that the result of slugifying e.g. Cyrillic text will not be an empty
    string, and can thus be safely used as an identifier (albeit not a human-readable one).
    """
    value = force_str(value)
```
